// <auto-generated />
using System;
using GeoChat.ChatAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeoChat.ChatAPI.Migrations
{
    [DbContext(typeof(ChatDBContext))]
    partial class ChatDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("GeoChat.ChatAPI.Entities.Chat", b =>
                {
                    b.Property<Guid>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SendTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            ChatId = new Guid("c0bc0ef8-5708-492f-aa49-da2d150e2835"),
                            Message = "Hi, I am your new agent.",
                            RoomId = new Guid("0d0b9a01-7246-4fb1-ac70-2f2c5d5f084b"),
                            SendTime = 1706942491L,
                            UserId = "agent1"
                        },
                        new
                        {
                            ChatId = new Guid("c68605be-7e12-4710-ae48-bf5d70c89868"),
                            Message = "Hi Okk ...",
                            RoomId = new Guid("0d0b9a01-7246-4fb1-ac70-2f2c5d5f084b"),
                            SendTime = 1706942611L,
                            UserId = "slave1"
                        },
                        new
                        {
                            ChatId = new Guid("e0bc032f-5728-484f-ad49-da2d150e5415"),
                            Message = "U have been declared a slave henceforth",
                            RoomId = new Guid("65958d08-4e33-40da-a0ac-54442fba0abe"),
                            SendTime = 1706882313L,
                            UserId = "sayan83"
                        },
                        new
                        {
                            ChatId = new Guid("d44facf9-d3f3-4f2b-baa0-15d62ed3d656"),
                            Message = "Ok Boss",
                            RoomId = new Guid("65958d08-4e33-40da-a0ac-54442fba0abe"),
                            SendTime = 1706882333L,
                            UserId = "slave1"
                        },
                        new
                        {
                            ChatId = new Guid("3362357a-2811-4100-9207-bf77e5b991ed"),
                            Message = "Good! Get me some whiskey",
                            RoomId = new Guid("65958d08-4e33-40da-a0ac-54442fba0abe"),
                            SendTime = 1706896187L,
                            UserId = "sayan83"
                        },
                        new
                        {
                            ChatId = new Guid("0b62f0c5-f566-4700-b122-9f852eedf07e"),
                            Message = "Toki for u boss ...",
                            RoomId = new Guid("65958d08-4e33-40da-a0ac-54442fba0abe"),
                            SendTime = 1706896238L,
                            UserId = "slave1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
